### ISSUE TITLE
Name of app

### ISSUE THREAD

**Issue by nogainbar** [InFact-coop/Stimmy-things#16]
hey @moghraby!

We have a question regarding the name of the app:

from a bit of research, I can see that 'stims' are mainly related to Autism: https://actuallyadhd.tumblr.com/post/60959486041/stimming

However, we really love the name Stimmy things!!!

What do you think about this name for this app? is it appropriate?

thank you
Noga

**Comment by moghraby** [comment]
well it is a bit of an odd name but actually this would be fine. 
we would have to explain it at the start  so people know what we are talking about.
